// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odnhufdhjcdcdzdkqxkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbmh1ZmRoamNkY2R6ZGtxeGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzYzNTYsImV4cCI6MjA3MjcxMjM1Nn0.5TeKngGho8ifJ1yVwnCkqoXUmJZ-TbXWB7FiDYUDMOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});